/** Marcas de veículos mais vendidas e comuns no mercado brasileiro. */
export const CAR_BRANDS = [
  "Fiat",
  "Volkswagen",
  "Chevrolet",
  "Toyota",
  "Hyundai",
  "Renault",
  "Jeep",
  "Honda",
  "Nissan",
  "Ford",
  "Mitsubishi",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Peugeot",
  "Citroën",
  "Chery",
  "BYD",
  "GWM",
  "Kia",
  "RAM",
  "Land Rover",
  "Volvo",
  "Suzuki",
  "JAC",
  "Haval",
  "Mini",
  "Porsche",
  "Subaru",
  "Iveco",
] as const;

export type CarBrand = (typeof CAR_BRANDS)[number];
