/** Campos da vistoria usados na emissão do laudo (Edge). */
export type OfficialInspection = {
  inspection_number: number;
  inspection_date: string;
  inspection_time?: string | null;
  location?: string | null;
  inspection_purpose?: string | null;
  plate: string | null;
  chassis: string | null;
  renavam?: string | null;
  brand?: string | null;
  model?: string | null;
  version?: string | null;
  color?: string | null;
  fuel?: string | null;
  manufacture_year?: number | null;
  model_year?: number | null;
  mileage?: number | null;
  motor_number?: string | null;
  vehicle_uf?: string | null;
  registration_city_uf?: string | null;
  vehicle_category?: string | null;
  vehicle_species?: string | null;
  passenger_capacity?: number | null;
  power_cv?: number | null;
  engine_displacement?: number | null;
  situation?: string | null;
  market_fipe_value?: number | null;
  market_average_value?: number | null;
  insurance_acceptance_percent?: number | null;
  vehicle_condition?: string | null;
  is_armored?: boolean | null;
  buyer_name?: string | null;
  buyer_document?: string | null;
  seller_name?: string | null;
  seller_document?: string | null;
  client_name?: string | null;
  client_document?: string | null;
  client_phone?: string | null;
  client_email?: string | null;
  requester_name?: string | null;
  requester_document?: string | null;
  opinion?: string | null;
  technical_notes?: string | null;
};
